version: '3'
services:

  db:
    image: mysql:8.0.31 # 컨테이너에서 사용하는 base image 지정
    restart: always # 컨테이너 다운 시 재시작하라는 명령어
    volumes: # -v 옵션과 동일
      - ./mysqldata:/var/lib/mysql
    environment: # 컨테이너 안의 환경변수 설정
      - MYSQL_ROOT_PASSWORD=12345
    ports: # -p 옵션과 동일
      - 3306:3306
      -

  web:
    container_name: web
    restart: always
    image: chlalswns200/web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    restart: always
    image: chlalswns200/nginx
    ports:
      - 80:80
    depends_on:
      - web